# Generated by Django 5.1.2 on 2024-10-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodels',
            old_name='video',
            new_name='video_file',
        ),
    ]
