# Generated by Django 5.1.2 on 2024-10-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0002_rename_video_videomodels_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodels',
            name='description',
        ),
    ]
