# Generated by Django 5.1.2 on 2024-10-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0004_remove_videomodels_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodels',
            name='title',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
