# Generated by Django 5.1.2 on 2024-10-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0005_videomodels_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodels',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
