# Generated by Django 5.1.2 on 2024-10-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0006_videomodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodels',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
