# Generated by Django 5.1.2 on 2024-10-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0007_alter_videomodels_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodels',
            name='slug',
        ),
    ]
