# Generated by Django 5.1.2 on 2024-10-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0008_remove_videomodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodels',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
